---
- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes

- name: Install software-properties-common
  apt:
    name: software-properties-common
    state: present
    force_apt_get: true

- name: Add certbot repositories
  apt_repository:
    repo: ppa:certbot/certbot
    update_cache: true

- name: Install certbot
  apt:
    name: certbot
    state: present
    force_apt_get: true

- name: Install urllib3, chardet
  pip:
    name:
      - urllib3=={{ urllib3_version }}
      - chardet=={{ chardet_version }}
    extra_args: --upgrade
    executable: /usr/bin/pip3
  become: true

- name: Check if certificate already exists.
  stat:
    path: /etc/letsencrypt/live/{{ vault_domain }}/cert.pem
  register: letsencrypt_cert

- name: Generate new certificate if one doesn't exist.
  shell: "certbot certonly --standalone --noninteractive --agree-tos --email `
  ` {{ letsencrypt_email }} -d {{ vault_domain }}"
  changed_when: false
  when: not letsencrypt_cert.stat.exists

- name: Add letsencrypt cronjob for cert renewal
  cron:
    name: letsencrypt_renewal
    special_time: weekly
    job: "certbot certonly --standalone --noninteractive --agree-tos --email \
    {{ letsencrypt_email }} -d {{ vault_domain }}"
